# Gunakan image Node resmi (alpine = ringan)
FROM node:20-alpine

# Install dependencies dasar (termasuk openssl untuk Prisma)
RUN apk add --no-cache bash openssl

# Direktori kerja di dalam container
WORKDIR /app

# Salin file dependency
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Salin semua source code
COPY . .

# Salin file .env (pastikan file ini ada di root project)
COPY .env .env

# Generate Prisma Client 
RUN npx prisma 
RUN npx prisma generate

# Build NestJS
RUN yarn build

# Buka port aplikasi
EXPOSE 4001

# Jalankan aplikasi
CMD ["node", "dist/src/main"]
